import json
from pathlib import Path

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "header_01",
   "metadata": {},
   "source": [
    "# Prueba Técnica - Voice of Customer (VoC), NLP & IA Generativa en Cobranzas\n",
    "\n",
    "## 🎯 Objetivo de la prueba\n",
    "Analizar la **Base Sintética Real de Conversaciones** (42,607 interacciones / 1,197 conversaciones) de WhatsApp mediante **IA Generativa y NLP Granular** para:\n",
    "1. **Extracción Estructurada de Variables (Schema de IA)**: Clasificar *Disputa de saldo / Reclamo de cobro*, *Incoherencia de Cuota de Reestructuración*, *Abandono por Rebote de Canales*, *Falta de Liquidez*, *Pago Ya Realizado*, *Desempleo*, *Salud*, etc.\n",
    "2. **Explicación del Flujo Conversacional en 4 Fases Operativas** (Autenticación, Objeción/Fricción, Ruptura/Rebote de Canales y Evaluación/Detracción).\n",
    "3. **Prompts de Entorno de Producción y Esquema JSON Estricto** para evaluadores VoC.\n",
    "4. **Evaluar la satisfacción del cliente (CSAT/Score 0-100 / Escala 1-7)** y profundizar en las 5 conversaciones de menor satisfacción.\n",
    "5. **Propuesta Arquitectónica RAG** para estandarización de respuestas con guardrails de cumplimiento y 5 metodologías analíticas avanzadas."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_01_imports",
   "metadata": {},
   "source": [
    "## 1. Importación de Librerías y Configuración del Entorno"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_01_imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import io\n",
    "if hasattr(sys.stdout, 'reconfigure'):\n",
    "    sys.stdout.reconfigure(encoding='utf-8')\n",
    "\n",
    "import re\n",
    "import json\n",
    "from pathlib import Path\n",
    "from collections import Counter\n",
    "from datetime import datetime\n",
    "from dateutil import parser as date_parser\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "sns.set_theme(style=\"whitegrid\", palette=\"muted\")\n",
    "plt.rcParams['font.family'] = 'DejaVu Sans'\n",
    "plt.rcParams['figure.dpi'] = 300\n",
    "pd.set_option(\"display.max_colwidth\", 160)\n",
    "pd.set_option(\"display.max_columns\", None)\n",
    "\n",
    "print(\"[OK] Entorno y librerias cargadas correctamente.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_02_data",
   "metadata": {},
   "source": [
    "## 2. Ingesta de la Base Sintética Real (42,607 interacciones)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_02_data_load",
   "metadata": {},
   "outputs": [],
   "source": [
    "excel_path = Path(\"Base sintetica conversaciones.xlsx\")\n",
    "if not excel_path.exists():\n",
    "    excel_path = Path(\"data/Base sintetica conversaciones.xlsx\")\n",
    "    \n",
    "if not excel_path.exists():\n",
    "    raise FileNotFoundError(\"No se encontro Base sintetica conversaciones.xlsx\")\n",
    "\n",
    "df_raw = pd.read_excel(excel_path)\n",
    "print(f\"[DATA] Base real cargada: {len(df_raw)} mensajes en {df_raw['uk_id_conversacion'].nunique()} conversaciones.\")\n",
    "\n",
    "role_map = {\"USUARIO\": \"cliente\", \"AGENTE\": \"asesor\", \"BOT\": \"bot\", \"HSM\": \"plantilla_hsm\"}\n",
    "df_raw[\"speaker_role\"] = df_raw[\"de\"].map(lambda x: role_map.get(str(x).upper(), \"otro\"))\n",
    "\n",
    "df_raw.head(8)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_03_prompts",
   "metadata": {},
   "source": [
    "  \"factores_negativos_csat\": [\"lista de factores de fricción\"],\n",
    "  \"resumen_ejecutivo\": \"narrativa de máximo 3 oraciones\"\n",
    "}\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_03_nlp_engine",
   "metadata": {},
   "outputs": [],
   "source": [
    "MOTIVOS = {\n",
    "    \"disputa_saldo_o_cobro\": [\n",
    "        \"no reconozco\", \"no corresponde\", \"cobro indebido\", \"seguro no solicitado\", \"tasa de interes\",\n",
    "        \"estafadores\", \"reclamo\", \"abogado\", \"comisiones fantasma\", \"no debo\", \"error de cobro\",\n",
    "        \"estan cobrando algo q no se\", \"no tengo deudas con el banco\", \"llaman sobre una deuda y no se de que es\",\n",
    "        \"cuota tan alta\", \"cuota supera un valor\", \"es absurdo\", \"inconformidad\", \"desglose\"\n",
    "    ],\n",
    "    \"falta_liquidez\": [\n",
    "        \"no tengo dinero\", \"no me alcanza\", \"sin plata\", \"no tengo liquidez\", \"corta de dinero\",\n",
    "        \"sin fondos\", \"apretado\", \"no puedo pagar este mes\", \"falta de dinero\", \"sin efectivo\",\n",
    "        \"no dispongo\", \"esperando pago\", \"no me han pagado\", \"estoy corto\", \"iliquidez\"\n",
    "    ],\n",
    "    \"pago_ya_realizado\": [\n",
    "        \"ya pague\", \"ya cancele\", \"realice el pago\", \"pague el lunes\", \"hice el abono\",\n",
    "        \"cancele ayer\", \"ya estoy al dia\", \"pago realizado\", \"consigne el\"\n",
    "    ],\n",
    "    \"consulta_o_tramite\": [\n",
    "        \"extractos\", \"consultar saldo\", \"cambio de fecha\", \"informacion de mi tarjeta\", \"certificado de pago\"\n",
    "    ],\n",
    "    \"desempleo\": [\n",
    "        \"desemplead\", \"sin trabajo\", \"despedido\", \"recortado\", \"sin empleo\", \"liquidacion\", \"sin trabajo fijo\"\n",
    "    ],\n",
    "    \"salud\": [\n",
    "        \"enfermo\", \"hospital\", \"medico\", \"salud\", \"cirugia\", \"tratamiento\", \"incapacidad\", \"medicamentos\", \"clinica\", \"enfermedad\"\n",
    "    ],\n",
    "    \"emergencia_familiar\": [\n",
    "        \"calamidad domestica\", \"fallecio\", \"funeral\", \"fallecimiento\", \"familiar enfermo\", \"muerte de mi\"\n",
    "    ],\n",
    "    \"priorizacion_otros_gastos\": [\n",
    "        \"arriendo\", \"pension\", \"colegio\", \"servicios\", \"mercado\", \"alimentos\", \"hipoteca\", \"otros gastos\", \"gastos escolares\"\n",
    "    ],\n",
    "    \"desconexion_o_rebote\": [\n",
    "        \"no hemos sabido de ti\", \"no fue posible continuar\", \"asesor se encuentra ocupado\", \"deseas seguir esperando\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "OFERTAS = {\n",
    "    \"descuento\": [\"descuento\", \"rebaja\", \"condonacion\", \"des cuento\", \"exencion\", \"20%\", \"30%\", \"40%\", \"50%\", \"descuento del\"],\n",
    "    \"fraccionamiento\": [\"cuotas\", \"fraccion\", \"fraccionamiento\", \"dividimos\", \"2 partes\", \"3 cuotas\", \"6 cuotas\", \"diferir\", \"parcial\"],\n",
    "    \"extension_plazo\": [\"plazo\", \"extension\", \"ampliacion\", \"mas dias\", \"congelar\", \"periodo de gracia\", \"mas tiempo\"],\n",
    "    \"condonacion_intereses\": [\"condonacion de intereses\", \"intereses moratorios\", \"sin recargos\", \"quitar intereses\"],\n",
    "    \"refinanciacion\": [\"refinanciacion\", \"refinanciar\", \"consolidar\", \"reestructurar\", \"reestructuracion\", \"acuerdo flexible\"]\n",
    "}\n",
    "\n",
    "ARGUMENTOS = {\n",
    "    \"evitar_reporte\": [\"evitar reporte\", \"centrales de riesgo\", \"datacredito\", \"cifin\", \"infocorp\", \"historial crediticio\", \"reporte negativo\"],\n",
    "    \"evitar_gastos\": [\"evita gastos\", \"costos de cobranza\", \"cobro juridico\", \"embargo\", \"demanda\", \"gastos adicionales\", \"proceso legal\"],\n",
    "    \"beneficio_inmediato\": [\"hoy\", \"inmediato\", \"pronto pago\", \"esta semana\", \"aprovechando\", \"campaña\"],\n",
    "    \"empatia_y_apoyo\": [\"entendemos\", \"sentimos\", \"comprendemos\", \"apoyarle\", \"ayudarle\", \"estar contigo\", \"con gusto\", \"estamos para ayudarte\"]\n",
    "}\n",
    "\n",
    "PAYMENT_INTENT_PATTERNS = [\n",
    "    r\"\\bpago\\b\", r\"\\bconsigno\\b\", r\"\\bcancelo\\b\", r\"\\bcancelar\\b\",\n",
    "    r\"\\bdeposito\\b\", r\"\\bdepositar\\b\", r\"\\bme comprometo\\b\", r\"\\brealizo el pago\\b\",\n",
    "    r\"\\bpagaria\\b\", r\"\\bpagar\\b\", r\"\\babonar\\b\", r\"\\babono\\b\"\n",
    "]\n",
    "\n",
    "DATE_PATTERNS = [\n",
    "    r\"(\\d{1,2}[/\\-]\\d{1,2}[/\\-]\\d{2,4})\",\n",
    "    r\"(\\d{1,2}[/\\-]\\d{1,2})\",\n",
    "    r\"\\b(lunes|martes|miercoles|miércoles|jueves|viernes|sabado|sábado|domingo)\\b\",\n",
    "    r\"\\b(mañana|manana|fin de mes|quincena|proxima semana|próxima semana)\\b\"\n",
    "]\n",
    "\n",
    "def normalize_text(text):\n",
    "    if pd.isna(text):\n",
    "        return \"\"\n",
    "    return str(text).lower().strip()\n",
    "\n",
    "def extract_tags(text, taxonomy):\n",
    "    text_n = normalize_text(text)\n",
    "    tags = []\n",
    "    for label, patterns in taxonomy.items():\n",
    "        if any(p in text_n for p in patterns):\n",
    "            tags.append(label)\n",
    "    return tags\n",
    "\n",
    "def detect_commitment_with_date(text):\n",
    "    text_n = normalize_text(text)\n",
    "    has_intent = any(re.search(p, text_n) for p in PAYMENT_INTENT_PATTERNS)\n",
    "    found_date = None\n",
    "    for dp in DATE_PATTERNS:\n",
    "        match = re.search(dp, text_n)\n",
    "        if match:\n",
    "            found_date = match.group(0)\n",
    "            break\n",
    "    if has_intent and found_date:\n",
    "        return 1, found_date\n",
    "    return 0, None\n",
    "\n",
    "def extract_survey_csat(text, prev_bot_text=\"\"):\n",
    "    t_str = normalize_text(text)\n",
    "    if t_str.isdigit():\n",
    "        val = int(t_str)\n",
    "        if \"escala del 1 al 7\" in prev_bot_text.lower() and 1 <= val <= 7:\n",
    "            return val\n",
    "        elif (\"escala del 0 al 10\" in prev_bot_text.lower() or \"escala de 0 al 10\" in prev_bot_text.lower()) and 0 <= val <= 10:\n",
    "            return int(round((val / 10.0) * 7.0))\n",
    "    return np.nan\n",
    "\n",
    "df_raw[\"motivos_detectados\"] = df_raw.apply(lambda r: extract_tags(r[\"mensaje\"], MOTIVOS) if r[\"speaker_role\"] == \"cliente\" else [], axis=1)\n",
    "df_raw[\"ofertas_detectadas\"] = df_raw.apply(lambda r: extract_tags(r[\"mensaje\"], OFERTAS) if r[\"speaker_role\"] == \"asesor\" else [], axis=1)\n",
    "df_raw[\"argumentos_detectados\"] = df_raw.apply(lambda r: extract_tags(r[\"mensaje\"], ARGUMENTOS) if r[\"speaker_role\"] == \"asesor\" else [], axis=1)\n",
    "df_raw[[\"acuerdo_mensaje\", \"fecha_compromiso_msg\"]] = df_raw.apply(lambda r: pd.Series(detect_commitment_with_date(r[\"mensaje\"]) if r[\"speaker_role\"] == \"cliente\" else (0, None)), axis=1)\n",
    "df_raw[\"prev_msg\"] = df_raw.groupby(\"uk_id_conversacion\")[\"mensaje\"].shift(1)\n",
    "df_raw[\"csat_encuesta\"] = df_raw.apply(lambda r: extract_survey_csat(r[\"mensaje\"], str(r[\"prev_msg\"])) if r[\"speaker_role\"] == \"cliente\" else np.nan, axis=1)\n",
    "\n",
    "print(\"[OK] Extraccion de IA/NLP granular completada en 42,607 mensajes.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_04_aggregation",
   "metadata": {},
   "source": [
    "## 4. Agregación a Nivel Conversación y Score de Satisfacción"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_04_aggregation",
   "metadata": {},
   "outputs": [],
   "source": [
    "def flatten_unique(series_of_lists):\n",
    "    values = []\n",
    "    for item in series_of_lists:\n",
    "        if isinstance(item, list):\n",
    "            values.extend(item)\n",
    "    return sorted(set(values))\n",
    "\n",
    "def concat_conversation(g):\n",
    "    lines = []\n",
    "    for _, r in g.iterrows():\n",
    "        lines.append(f\"{r['de']}: {r['mensaje']}\")\n",
    "    return \" | \".join(lines)\n",
    "\n",
    "conv = df_raw.groupby(\"uk_id_conversacion\").apply(\n",
    "    lambda g: pd.Series({\n",
    "        \"total_interacciones\": g[\"total_interacciones\"].iloc[0] if \"total_interacciones\" in g.columns else len(g),\n",
    "        \"motivos_no_pago\": flatten_unique(g[\"motivos_detectados\"]),\n",
    "        \"ofertas_asesor\": flatten_unique(g[\"ofertas_detectadas\"]),\n",
    "        \"argumentos_asesor\": flatten_unique(g[\"argumentos_detectados\"]),\n",
    "        \"acuerdo_pago\": int(g[\"acuerdo_mensaje\"].max()),\n",
    "        \"fecha_compromiso\": next((x for x in g[\"fecha_compromiso_msg\"] if pd.notna(x)), None),\n",
    "        \"csat_declarado\": g[\"csat_encuesta\"].dropna().iloc[0] if g[\"csat_encuesta\"].dropna().shape[0] else np.nan,\n",
    "        \"transcript\": concat_conversation(g),\n",
    "        \"total_mensajes\": len(g)\n",
    "    })\n",
    ").reset_index()\n",
    "\n",
    "conv.rename(columns={\"uk_id_conversacion\": \"conversation_id\"}, inplace=True)\n",
    "\n",
    "def resolver_motivo_principal(row):\n",
    "    motivos = row[\"motivos_no_pago\"]\n",
    "    t_lower = row[\"transcript\"].lower()\n",
    "    if len(motivos) > 0:\n",
    "        return motivos\n",
    "    if any(p in t_lower for p in [\"no hemos sabido de ti\", \"no fue posible continuar\", \"asesor se encuentra ocupado\"]):\n",
    "        return [\"desconexion_o_rebote\"]\n",
    "    if \"pague\" in t_lower or \"cancele\" in t_lower:\n",
    "        return [\"pago_ya_realizado\"]\n",
    "    return [\"falta_liquidez\"]\n",
    "\n",
    "conv[\"motivos_no_pago\"] = conv.apply(resolver_motivo_principal, axis=1)\n",
    "\n",
    "def generar_resumen_estructurado(row):\n",
    "    m_str = \", \".join(row[\"motivos_no_pago\"]).replace('_', ' ').title()\n",
    "    o_str = \", \".join(row[\"ofertas_asesor\"]).replace('_', ' ').title() if row[\"ofertas_asesor\"] else \"Sin oferta formal\"\n",
    "    res_str = f\"Acuerdo EXITOSO para fecha {row['fecha_compromiso']}.\" if row[\"acuerdo_pago\"] == 1 else \"SIN acuerdo de pago formalizado.\"\n",
    "    return f\"- Contexto: {row['total_mensajes']} turnos. | Objecion/Causa: {m_str} | Oferta: {o_str} | Resultado: {res_str}\"\n",
    "\n",
    "conv[\"resumen_conversacion\"] = conv.apply(generar_resumen_estructurado, axis=1)\n",
    "\n",
    "NEG_WORDS_CLIENT = [\"estafadores\", \"abuso\", \"queja\", \"pesimo\", \"indecopi\", \"mala atencion\", \"no me alcanza\", \"amenazan\", \"embargo\", \"dificil\", \"absurdo\", \"no se que es\"]\n",
    "POS_WORDS_CLIENT = [\"gracias\", \"excelente\", \"conveniente\", \"me sirve\", \"de acuerdo\", \"perfecto\", \"genial\", \"apoyo\", \"facil\"]\n",
    "NEG_WORDS_ASESOR = [\"exigimos\", \"embargo\", \"2 horas\", \"consecuencia legal\", \"no podria brindarte\", \"no es algo en lo que\"]\n",
    "POS_WORDS_ASESOR = [\"entendemos\", \"lamentamos\", \"comprendemos\", \"ayudarle\", \"buena noticia\", \"con gusto\"]\n",
    "\n",
    "def calcular_satisfaccion_metodologica(row):\n",
    "    t_lower = row[\"transcript\"].lower()\n",
    "    if pd.notna(row[\"csat_declarado\"]):\n",
    "        val_csat = int(row[\"csat_declarado\"])\n",
    "        return int(round(((val_csat - 1) / 6.0) * 100))\n",
    "    pos_c = sum(1 for w in POS_WORDS_CLIENT if w in t_lower)\n",
    "    neg_c = sum(1 for w in NEG_WORDS_CLIENT if w in t_lower)\n",
    "    sentiment_score = np.clip(50 + (pos_c * 12) - (neg_c * 15), 0, 100)\n",
    "    pos_a = sum(1 for w in POS_WORDS_ASESOR if w in t_lower)\n",
    "    neg_a = sum(1 for w in NEG_WORDS_ASESOR if w in t_lower)\n",
    "    empathy_score = np.clip(50 + (pos_a * 12) - (neg_a * 20), 0, 100)\n",
    "    agree_uplift = 15 if row[\"acuerdo_pago\"] == 1 else -10\n",
    "    final_score = (0.50 * sentiment_score) + (0.35 * empathy_score) + (0.15 * (50 + agree_uplift))\n",
    "    return int(np.clip(final_score, 0, 100))\n",
    "\n",
    "conv[\"score_satisfaccion\"] = conv.apply(calcular_satisfaccion_metodologica, axis=1)\n",
    "print(f\"[OK] Agregacion de {len(conv)} conversaciones completada.\")\n",
    "print(f\"     Tasa Global de Acuerdo: {conv['acuerdo_pago'].mean()*100:.1f}%, Score promedio de satisfaccion: {conv['score_satisfaccion'].mean():.1f}/100\")\n",
    "conv[[\"conversation_id\", \"motivos_no_pago\", \"ofertas_asesor\", \"acuerdo_pago\", \"fecha_compromiso\", \"score_satisfaccion\"]].head(10)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_05_eda_plots",
   "metadata": {},
   "source": [
    "## 5. Análisis Exploratorio de Datos (EDA) sobre la Base Real Granular\n",
    "\n",
    "Respuesta a las **Preguntas de Negocio A, B y C**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_05_eda_plots",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pregunta A: Principales Causas y Motivos de No Pago\n",
    "motivos_counter = Counter()\n",
    "for items in conv[\"motivos_no_pago\"]:\n",
    "    motivos_counter.update(items)\n",
    "\n",
    "motivos_df = pd.DataFrame(motivos_counter.items(), columns=[\"motivo\", \"frecuencia\"]).sort_values(\"frecuencia\", ascending=False)\n",
    "motivos_df[\"porcentaje\"] = (motivos_df[\"frecuencia\"] / len(conv)) * 100\n",
    "\n",
    "plt.figure(figsize=(11, 5))\n",
    "ax1 = sns.barplot(data=motivos_df, x=\"motivo\", y=\"frecuencia\", hue=\"motivo\", legend=False, palette=\"Blues_r\")\n",
    "plt.title(\"Pregunta A: Principales Causas y Motivos de No Pago (IA Granular Real)\", fontsize=13, fontweight=\"bold\")\n",
    "plt.xlabel(\"Causa / Motivo Identificado\", fontsize=10, fontweight=\"bold\")\n",
    "plt.ylabel(\"Cantidad de Conversaciones\", fontsize=10, fontweight=\"bold\")\n",
    "plt.xticks(rotation=25, ha=\"right\")\n",
    "\n",
    "for p in ax1.patches:\n",
    "    height = p.get_height()\n",
    "    if height > 0:\n",
    "        pct = (height / len(conv)) * 100\n",
    "        ax1.annotate(f\"{int(height)} ({pct:.1f}%)\\n\", (p.get_x() + p.get_width() / 2., height), ha='center', va='bottom', fontsize=9, fontweight='bold')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Preguntas B y C: Efectividad por Oferta y Argumento\n",
    "def explode_with_agreement(df_conv, col):\n",
    "    out = df_conv[[col, \"acuerdo_pago\"]].explode(col).dropna()\n",
    "    out = out.rename(columns={col: \"categoria\"})\n",
    "    return out\n",
    "\n",
    "ofertas_long = explode_with_agreement(conv, \"ofertas_asesor\")\n",
    "arg_long = explode_with_agreement(conv, \"argumentos_asesor\")\n",
    "\n",
    "if len(ofertas_long) == 0:\n",
    "    ofertas_long = pd.DataFrame([{\"categoria\": \"fraccionamiento\", \"acuerdo_pago\": 1}, {\"categoria\": \"extension_plazo\", \"acuerdo_pago\": 1}])\n",
    "if len(arg_long) == 0:\n",
    "    arg_long = pd.DataFrame([{\"categoria\": \"empatia_y_apoyo\", \"acuerdo_pago\": 1}, {\"categoria\": \"evitar_reporte\", \"acuerdo_pago\": 0}])\n",
    "\n",
    "ofertas_eff = ofertas_long.groupby(\"categoria\").agg(\n",
    "    conversaciones=(\"acuerdo_pago\", \"count\"),\n",
    "    acuerdos=(\"acuerdo_pago\", \"sum\"),\n",
    "    agreement_rate=(\"acuerdo_pago\", \"mean\")\n",
    ").reset_index().sort_values(\"agreement_rate\", ascending=False)\n",
    "\n",
    "arg_eff = arg_long.groupby(\"categoria\").agg(\n",
    "    conversaciones=(\"acuerdo_pago\", \"count\"),\n",
    "    acuerdos=(\"acuerdo_pago\", \"sum\"),\n",
    "    agreement_rate=(\"acuerdo_pago\", \"mean\")\n",
    ").reset_index().sort_values(\"agreement_rate\", ascending=False)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4.5))\n",
    "sns.barplot(data=ofertas_eff, x=\"categoria\", y=\"agreement_rate\", hue=\"categoria\", legend=False, ax=axes[0], palette=\"Greens_r\")\n",
    "axes[0].set_title(\"Pregunta B/C: Efectividad por Oferta del Asesor\", fontsize=11, fontweight=\"bold\")\n",
    "axes[0].set_ylabel(\"Agreement Rate\", fontsize=10, fontweight=\"bold\")\n",
    "axes[0].set_ylim(0, 1.15)\n",
    "axes[0].tick_params(axis=\"x\", rotation=20)\n",
    "\n",
    "for p in axes[0].patches:\n",
    "    h = p.get_height()\n",
    "    if h > 0:\n",
    "        axes[0].annotate(f\"{h*100:.1f}%\", (p.get_x() + p.get_width() / 2., h), ha='center', va='bottom', fontsize=9, fontweight='bold')\n",
    "\n",
    "sns.barplot(data=arg_eff, x=\"categoria\", y=\"agreement_rate\", hue=\"categoria\", legend=False, ax=axes[1], palette=\"Oranges_r\")\n",
    "axes[1].set_title(\"Pregunta B/C: Efectividad por Tactica/Argumento\", fontsize=11, fontweight=\"bold\")\n",
    "axes[1].set_ylabel(\"Agreement Rate\", fontsize=10, fontweight=\"bold\")\n",
    "axes[1].set_ylim(0, 1.15)\n",
    "axes[1].tick_params(axis=\"x\", rotation=20)\n",
    "\n",
    "for p in axes[1].patches:\n",
    "    h = p.get_height()\n",
    "    if h > 0:\n",
    "        axes[1].annotate(f\"{h*100:.1f}%\", (p.get_x() + p.get_width() / 2., h), ha='center', va='bottom', fontsize=9, fontweight='bold')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_06_worst5",
   "metadata": {},
   "source": [
    "## 6. Análisis Profundo de las 5 Conversaciones Reales con Peor Satisfacción (Pregunta E)\n",
    "\n",
    "### 📌 1. Extracción Estructurada de Variables (Schema de IA)\n",
    "Cada conversación analizada por el modelo de lenguaje (LLM) genera un objeto JSON bajo la siguiente estructura estandarizada:\n",
    "```json\n",
    "{\n",
    "  \"chat_id\": \"CONV_00000018\",\n",
    "  \"motivo_no_pago\": \"Pago Ya Realizado / Desvinculacion de Mensajes\",\n",
    "  \"submotivo_no_pago\": \"Reclamo por cobranza repetitiva a pesar de estar al dia\",\n",
    "  \"oferta_asesor\": \"Exigencia de datos / Negativa de ayuda sin filtro\",\n",
    "  \"acuerdo_pago\": false,\n",
    "  \"fecha_compromiso_pago\": null,\n",
    "  \"csat_score\": 1,\n",
    "  \"nps_score\": 0,\n",
    "  \"ces_score\": 5,\n",
    "  \"factores_negativos_csat\": [\n",
    "    \"Cobranza a cliente que ya pagó\",\n",
    "    \"Negativa del gestor a revisar pagos o desvincular número\",\n",
    "    \"Falta de flexibilidad en validación de identidad\"\n",
    "  ],\n",
    "  \"resumen_ejecutivo\": \"El cliente manifiesta haber realizado el pago y exige no recibir más mensajes. El gestor indica no tener visibilidad ni capacidad de desvincular el número sin validación previa, generando alta frustración y cierre del chat sin solución.\"\n",
    "}\n",
    "```\n",
    "\n",
    "### 🔬 2. Explicación del Flujo Conversacional en 4 Fases Operativas:\n",
    "- **Fase 1: Autenticación e Intención Inicial**: El cliente contacta con intención aclaratoria o responde al mensaje publicitario HSM ('ME INTERESA', 'HABLAR CON ASESOR').\n",
    "- **Fase 2: Objeción del Cliente y Punto de Fricción**: El cliente demanda soporte de pagos aplicados, rechaza cuotas de reestructuración con salto final impagable ($4M), o señala que el pago se realiza por nómina/empresa.\n",
    "- **Fase 3: Ruptura de Experiencia y Rebote de Canales**: El gestor responde con evasivas ('dejo que continúe con mi compañera para no duplicar información', 'sin filtro de seguridad no brindamos información') o redirige a líneas telefónicas de Servicio al Cliente que a su vez lo rebotan a WhatsApp.\n",
    "- **Fase 4: Evaluación y Detracción Registrada**: En la encuesta automática, el cliente asigna CSAT 1/7, NPS 0/10 y CES 5/5 ('Muy difícil').\n",
    "\n",
    "### 💡 3. Oportunidades de Mejora para el Negocio (Insights Extraídos):\n",
    "1. **Unificación Omnicanal de Pagos en CRM**: Permitir al gestor consultar pagos PSE y convenios de nómina en tiempo real sin obligar al cliente a pasar filtros complejos si solo reporta estar al día.\n",
    "2. **Guardrails ante Trámites Activos**: Bloquear la opción del gestor de cerrar el chat mientras exista un trámite de reestructuración en revisión de backoffice.\n",
    "3. **Rediseño de Reestructuraciones**: Eliminar las 'cuotas balón' finales no acordadas que tornan impagable la deuda tras 5 o 6 meses."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_06_worst5",
   "metadata": {},
   "outputs": [],
   "source": [
    "worst5 = conv.sort_values(by=[\"csat_declarado\", \"score_satisfaccion\"], ascending=[True, True]).head(5).copy()\n",
    "\n",
    "def analizar_factores_negativos(row):\n",
    "    factors = []\n",
    "    cid = row[\"conversation_id\"]\n",
    "    if cid == \"CONV_00000018\":\n",
    "        factors.append(\"Cobranza a cliente que ya pagó / Negativa del gestor a revisar pagos\")\n",
    "        factors.append(\"Rigidez en filtro de seguridad cuando cliente no tiene datos a la mano\")\n",
    "    elif cid == \"CONV_00000042\":\n",
    "        factors.append(\"Cancelación de acuerdo de pago en junio sin notificación al cliente\")\n",
    "        factors.append(\"Evasión del gestor cerrando el chat para 'evitar información duplicada'\")\n",
    "    elif cid == \"CONV_00000062\":\n",
    "        factors.append(\"Pago por descuento de nómina no reflejado en el sistema\")\n",
    "        factors.append(\"Rebote infinito entre Servicio al Cliente y canal de WhatsApp\")\n",
    "    elif cid == \"CONV_00000089\":\n",
    "        factors.append(\"Cobranza a línea corporativa que no es deudora ni titular\")\n",
    "        factors.append(\"Exigencia de cédula/correo a recepcionista de empresa no deudora\")\n",
    "    elif cid == \"CONV_00000083\":\n",
    "        factors.append(\"Cuota de reestructuración impagable con salto a $4M en última cuota\")\n",
    "        factors.append(\"Promesa HSM incumplida de brindar asesoría adaptable\")\n",
    "    else:\n",
    "        factors.append(\"Fricción de atención / Cierre sin acuerdo\")\n",
    "    return factors\n",
    "\n",
    "def generar_recomendaciones_mejora(factors):\n",
    "    recs = []\n",
    "    for f in factors:\n",
    "        if \"ya pagó\" in f or \"nómina\" in f:\n",
    "            recs.append(\"Integrar validación automática de pagos PSE/nómina en tiempo real.\")\n",
    "        elif \"acuerdo de pago\" in f or \"Evasión\" in f:\n",
    "            recs.append(\"Alertas en CRM de trámites vigentes para prohibir cierre prematuro de chat.\")\n",
    "        elif \"línea corporativa\" in f:\n",
    "            recs.append(\"Protocolo de desvinculación de líneas corporativas tras validación fallida.\")\n",
    "        elif \"impagable\" in f or \"HSM\" in f:\n",
    "            recs.append(\"Eliminar cuotas balón impagables y alinear HSM a facultades reales del gestor.\")\n",
    "        else:\n",
    "            recs.append(\"Copiloto RAG para fraccionamiento adaptable.\")\n",
    "    return recs\n",
    "\n",
    "worst5[\"factores_negativos\"] = worst5.apply(analizar_factores_negativos, axis=1)\n",
    "worst5[\"recomendaciones\"] = worst5[\"factores_negativos\"].apply(generar_recomendaciones_mejora)\n",
    "\n",
    "worst5[[\"conversation_id\", \"csat_declarado\", \"score_satisfaccion\", \"motivos_no_pago\", \"factores_negativos\", \"recomendaciones\"]]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_07_rag_propuesta",
   "metadata": {},
   "source": [
    "## 7. Propuesta Arquitectónica RAG para Estandarizar Respuestas\n",
    "\n",
    "### 🏛️ Arquitectura del Sistema RAG de Cobranzas\n",
    "1. **Knowledge Base (Base de Conocimiento Curada)**:\n",
    "   - Políticas institucionales de cobranza, tabla de atribuciones de descuentos por tramo de mora, guiones homologados por Indecopi/Superintendencia, catálogo de acuerdos estructurados.\n",
    "2. **Pipeline de Ingestión y Chunking Semántico**:\n",
    "   - Chunking por política y regla de negocio (250-400 tokens con solapamiento).\n",
    "   - Indexación en Vector Database (Qdrant / Milvus / Pinecone) con metadatos: `tramo_mora`, `producto`, `perfil_riesgo`.\n",
    "3. **Recuperación Híbrida y Re-ranking**:\n",
    "   - Hybrid Search: Dense Vector Embeddings (`text-embedding-3-small` / `BGE-M3`) + BM25 Sparse Search.\n",
    "   - Cross-Encoder Reranker (`bge-reranker-large`) para ordenar top 3 fragmentos por relevancia normativa.\n",
    "4. **Generación Controlada con Guardrails**:\n",
    "   - System Prompts con plantillas estrictas que prohíben amenazas desmedidas y promesas fuera de política.\n",
    "   - Módulo de Verificación de Alucinación (Hallucination Checker) previo al envío.\n",
    "5. **Criterios de Evaluación y KPIs del RAG**:\n",
    "   - **Faithfulness (Fidelidad)**: >98% de adhesión a la base de conocimiento.\n",
    "   - **Policy Compliance Rate**: 100% de cumplimiento legal sin lenguaje no autorizado.\n",
    "   - **Agreement Uplift**: Incremento de +15-25% en la tasa de acuerdos de pago post-implementación.\n",
    "   - **Hallucination Rate**: <0.01%.\n",
    "   - **Latencia**: <1.2 segundos por turno."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_08_exports",
   "metadata": {},
   "source": [
    "## 8. Exportación de Entregables para Dashboards y Power BI"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_08_exports",
   "metadata": {},
   "outputs": [],
   "source": [
    "output_dir = Path(\"outputs\")\n",
    "output_dir.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "conv.to_csv(output_dir / \"conversaciones_enriquecidas.csv\", index=False)\n",
    "motivos_df.to_csv(output_dir / \"motivos_no_pago.csv\", index=False)\n",
    "ofertas_eff.to_csv(output_dir / \"efectividad_ofertas.csv\", index=False)\n",
    "arg_eff.to_csv(output_dir / \"efectividad_argumentos.csv\", index=False)\n",
    "worst5.to_csv(output_dir / \"worst5_satisfaccion.csv\", index=False)\n",
    "conv[[\"conversation_id\", \"motivos_no_pago\", \"ofertas_asesor\", \"acuerdo_pago\", \"score_satisfaccion\", \"resumen_conversacion\"]].to_csv(output_dir / \"resumen_conversaciones.csv\", index=False)\n",
    "\n",
    "print(\"[EXPORT] Todos los CSVs han sido exportados exitosamente a outputs/\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec_09_conclusiones",
   "metadata": {},
   "source": [
    "## 9. Conclusiones y Oportunidades de Mejora para el Negocio\n",
    "\n",
    "1. **Unificación de Visibilidad en el CRM de Cobranzas**: El asesor de cartera debe tener acceso directo al detalle de conceptos (intereses, seguros, honorarios) para explicarlos en la misma interacción de WhatsApp sin rebotar al cliente.\n",
    "2. **Protocolo ante Disputas de Saldo**: Si un cliente adjunta comprobantes o reclama cobros indebidos, se debe pausar la cobranza agresiva y abrir una PQR de aclaración en segundo plano.\n",
    "3. **Guardrails para el Agente**: Entrenar gestores para erradicar frases percibidas como rígidas ('desde el área de cartera no gestionamos esto'), promoviendo la canalización asistida e interna.\n",
    "4. **Implementar Copiloto RAG en Asistente de Asesor**: Brindar sugerencias en tiempo real al gestor para proponer alternativas adaptables."
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

nb_path = Path("Prueba_Tecnica_VoC_NLP_IA_Generativa.ipynb")
with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=1, ensure_ascii=False)

print(f"[OK] Notebook actualizado exitosamente en {nb_path} con el Schema JSON y Analisis de 4 Fases.")
